name = "wms-dashboard"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://gxngbvahywpaaavkkrfx.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4bmdidmFoeXdwYWFhdmtrcmZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxODE0NjYsImV4cCI6MjA5MDc1NzQ2Nn0.ADoZo0J1KJonkrUZN3XLPGi6vRrDgKM1I17ygN2RMeM"
